<?php
/**
 * Plugin Name: WP Lab Helper
 * Description: Local-only demo data, WooCommerce sandbox configuration and dummy payment gateway.
 * Version: 0.1.0
 */
if (!defined('ABSPATH')) exit;

add_filter('woocommerce_payment_gateways', function($g){ if(class_exists('WC_Payment_Gateway')) $g[]='WP_Lab_Dummy_Gateway'; return $g; });
add_action('plugins_loaded', function(){
  if(!class_exists('WC_Payment_Gateway')) return;
  class WP_Lab_Dummy_Gateway extends WC_Payment_Gateway {
    public function __construct(){
      $this->id='wp_lab_dummy'; $this->method_title='WP Lab Test Payment'; $this->method_description='Local sandbox payment simulator.';
      $this->has_fields=true; $this->supports=['products','refunds']; $this->init_form_fields(); $this->init_settings();
      $this->title=$this->get_option('title','Test Payment');
      add_action('woocommerce_update_options_payment_gateways_'.$this->id,[$this,'process_admin_options']);
    }
    public function init_form_fields(){ $this->form_fields=['enabled'=>['title'=>'Enable','type'=>'checkbox','label'=>'Enable WP Lab Test Payment','default'=>'yes'],'title'=>['title'=>'Title','type'=>'text','default'=>'Test Payment']]; }
    public function payment_fields(){
      echo '<p><strong>WP Lab dummy gateway</strong> — no money is moved.</p>';
      echo '<label>Result <select name="wp_lab_result"><option value="success">Successful</option><option value="failed">Failed</option><option value="pending">Pending</option><option value="on-hold">On hold</option></select></label>';
    }
    public function process_payment($order_id){
      $order=wc_get_order($order_id); $r=sanitize_text_field($_POST['wp_lab_result']??'success');
      if($r==='failed'){ wc_add_notice('WP Lab simulated decline.','error'); $order->update_status('failed','WP Lab simulated failure'); return ['result'=>'failure']; }
      if($r==='pending') $order->update_status('pending','WP Lab simulated pending payment');
      elseif($r==='on-hold') $order->update_status('on-hold','WP Lab simulated on-hold payment');
      else $order->payment_complete('WP-LAB-'.time());
      WC()->cart->empty_cart(); return ['result'=>'success','redirect'=>$this->get_return_url($order)];
    }
    public function process_refund($order_id,$amount=null,$reason=''){ $o=wc_get_order($order_id); if($o){$o->add_order_note('WP Lab simulated refund: '.$amount); return true;} return false; }
  }
});

function wp_lab_demo_blogs($n=10){
  $cats=['News','Guides','Insights','Updates']; foreach($cats as $c) wp_insert_term($c,'category');
  for($i=1;$i<=$n;$i++){
    $title="Sample Blog Post $i — ".['A Practical Guide','What You Need to Know','Tips and Ideas','Complete Overview'][($i-1)%4];
    wp_insert_post(['post_type'=>'post','post_status'=>'publish','post_title'=>$title,'post_excerpt'=>'A realistic sample excerpt for testing archive cards, spacing and typography.','post_content'=>"<p>This is sample content generated by WP Lab for theme testing.</p><h2>Overview</h2><p>Use this article to inspect typography, headings, links, paragraph spacing and responsive behavior.</p><h2>Key considerations</h2><ul><li>Readable content width</li><li>Heading hierarchy</li><li>Mobile spacing</li></ul><p><a href='#'>Sample inline link</a> for styling checks.</p>",'post_category'=>[get_cat_ID($cats[$i%4])]]);
  }
}
function wp_lab_demo_products($n=18){
  if(!class_exists('WC_Product_Simple')) return;
  foreach(['Featured','Everyday','Premium','Sale'] as $c) if(!term_exists($c,'product_cat')) wp_insert_term($c,'product_cat');
  for($i=1;$i<=$n;$i++){
    $p=new WC_Product_Simple(); $p->set_name($i===3?'A Product With An Intentionally Very Long Name To Test Card Wrapping And Responsive Layout':"Sample Product $i");
    $p->set_status('publish'); $p->set_regular_price((string)(10+$i*3)); if($i%4===0)$p->set_sale_price((string)(8+$i*2)); $p->set_manage_stock(true); $p->set_stock_quantity($i===7?0:20+$i); $p->set_description('<p>Sample product description generated by WP Lab for WooCommerce theme and checkout testing.</p>'); $p->set_short_description('Short sample description for product card and single-product testing.'); $p->save();
  }
  $v=new WC_Product_Variable(); $v->set_name('Sample Variable Product'); $v->set_status('publish'); $v->save();
}
function wp_lab_demo_orders($n=8){
  if(!function_exists('wc_create_order')) return;
  $products=wc_get_products(['limit'=>5,'status'=>'publish']);
  if(!$products) return;
  $states=['wc-processing','wc-completed','wc-pending','wc-on-hold','wc-refunded'];
  for($i=0;$i<$n;$i++){ $o=wc_create_order(); $o->add_product($products[$i%count($products)],1); $o->set_address(['first_name'=>'Demo','last_name'=>'Customer','email'=>"customer$i@example.test",'address_1'=>'123 Test Street','city'=>'Peshawar','country'=>'PK'],'billing'); $o->calculate_totals(); $o->update_status(str_replace('wc-','',$states[$i%count($states)])); }
}
function wp_lab_config_wc(){
  update_option('woocommerce_currency','PKR'); update_option('woocommerce_enable_guest_checkout','yes');
  update_option('woocommerce_cod_settings',['enabled'=>'yes','title'=>'Cash on Delivery']); update_option('woocommerce_bacs_settings',['enabled'=>'yes','title'=>'Direct Bank Transfer']);
  update_option('woocommerce_wp_lab_dummy_settings',['enabled'=>'yes','title'=>'Test Payment']);
  if(class_exists('WC_Shipping_Zone')){
    $zone=new WC_Shipping_Zone(); $zone->set_zone_name('Pakistan Test Zone'); $zone->add_location('PK','country'); $zone->save();
    foreach([['flat_rate',['cost'=>'250']],['free_shipping',['min_amount'=>'5000']],['local_pickup',[]]] as [$id,$opts]){ $inst=$zone->add_shipping_method($id); if($inst){ $methods=$zone->get_shipping_methods(); if(isset($methods[$inst])){ foreach($opts as $k=>$v)$methods[$inst]->update_option($k,$v); $methods[$inst]->update_option('enabled','yes'); } } }
  }
}
if(defined('WP_CLI') && WP_CLI){
  WP_CLI::add_command('wp-lab demo',function($args,$assoc){ wp_lab_demo_blogs((int)($assoc['blogs']??10)); wp_lab_demo_products((int)($assoc['products']??18)); wp_lab_demo_orders((int)($assoc['orders']??8)); WP_CLI::success('Demo blogs, products and orders generated.'); });
  WP_CLI::add_command('wp-lab configure-woocommerce',function(){ wp_lab_config_wc(); WP_CLI::success('WooCommerce sandbox configured.'); });
}

// Public preview support for temporary WP Lab tunnels.
function wp_lab_is_public_preview_request(){
  $host = strtolower($_SERVER['HTTP_HOST'] ?? '');
  return $host && $host !== 'localhost:8085' && $host !== '127.0.0.1:8085' && !str_starts_with($host,'localhost') && !str_starts_with($host,'127.0.0.1');
}
add_filter('pre_option_home', function($v){
  if(wp_lab_is_public_preview_request()){
    $scheme = (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) ? sanitize_text_field($_SERVER['HTTP_X_FORWARDED_PROTO']) : 'https');
    return $scheme.'://'.sanitize_text_field($_SERVER['HTTP_HOST']);
  }
  return $v;
});
add_filter('pre_option_siteurl', function($v){
  if(wp_lab_is_public_preview_request()){
    $scheme = (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) ? sanitize_text_field($_SERVER['HTTP_X_FORWARDED_PROTO']) : 'https');
    return $scheme.'://'.sanitize_text_field($_SERVER['HTTP_HOST']);
  }
  return $v;
});
add_action('init', function(){
  if(!wp_lab_is_public_preview_request()) return;
  $uri = $_SERVER['REQUEST_URI'] ?? '/';
  if(str_starts_with($uri,'/wp-admin') || str_starts_with($uri,'/wp-login.php')){
    status_header(403);
    nocache_headers();
    wp_die('WP Admin is disabled on this temporary client preview link.','WP Lab Preview',['response'=>403]);
  }
}, 0);
